[ZedternalReborn.Config_Objective]
MODEVERSION=20
Objective_bEnable=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Objective_Probability=(Normal=0.250000,Hard=0.250000,Suicidal=0.250000,HOE=0.250000,Custom=0.250000)
Objective_BaseDosh=(Normal=180,Hard=225,Suicidal=270,HOE=315,Custom=315)
Objective_PctOfWaveKilledForMaxReward=(Normal=0.650000,Hard=0.700000,Suicidal=0.750000,HOE=0.800000,Custom=0.800000)
Objective_DoshIncreaseModifierPerWave=(Normal=0.150000,Hard=0.100000,Suicidal=0.100000,HOE=0.050000,Custom=0.050000)

[ZedternalReborn.Config_SpecialWave]
MODEVERSION=20
SpecialWave_bAllowed=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
SpecialWave_Probability=(Normal=0.240000,Hard=0.240000,Suicidal=0.240000,HOE=0.240000,Custom=0.240000)
SpecialWave_DoubleProbability=(Normal=0.200000,Hard=0.200000,Suicidal=0.200000,HOE=0.200000,Custom=0.200000)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_ClotBuster",MinWave=0,MaxWave=8)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_CatchMe",MinWave=5,MaxWave=15)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_DoubleDamage",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Pop",MinWave=0,MaxWave=999) ;only headshot
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Popcorn",MinWave=0,MaxWave=999) ;only crwaler
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Regeneration",MinWave=0,MaxWave=999)
;SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Locked",MinWave=0,MaxWave=999) ;all door welded
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_GiftFromAbove",MinWave=0,MaxWave=999) ;reset ammo
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Vampire",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Earthquake",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Featherweight",MinWave=0,MaxWave=999) ;dead body on sky
;SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Shrink",MinWave=0,MaxWave=999) ;smaller when attack
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_GoredFast",MinWave=4,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Haemorrhage",MinWave=5,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_BuffUp",MinWave=6,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Virus",MinWave=3,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_UnlimitedAmmo",MinWave=10,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Fireworks",MinWave=5,MaxWave=999) ;many husk
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Predator",MinWave=6,MaxWave=999) ;friendly fp
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_BobbleZed",MinWave=6,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Dosh",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_GodMode",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Chaos",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_UpUpDecay",MinWave=0,MaxWave=999) ;dead body on sky hander
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Division",MinWave=0,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Emperor",MinWave=6,MaxWave=999) ;super sc
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Titans",MinWave=4,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Acceleration",MinWave=5,MaxWave=15)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_ToxicNightmare",MinWave=9,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_TheHorde",MinWave=11,MaxWave=999)
;SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_PurpleAlert",MinWave=13,MaxWave=999) ;only omega
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_HellFire",MinWave=10,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_FiveAlarmSiren",MinWave=7,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Poundamonium",MinWave=12,MaxWave=20)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Pesticide",MinWave=3,MaxWave=999) ;only crawler size up
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_BloodyChainsaw",MinWave=12,MaxWave=25)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_MechanicalProblem",MinWave=9,MaxWave=999) ;only dar
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Phoenix",MinWave=20,MaxWave=999)
SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_Lethargic",MinWave=0,MaxWave=999) ;fake zedtime
;SpecialWave_SpecialWaves=(Path="ZedternalReborn.WMSpecialWave_BackupPlan",MinWave=0,MaxWave=5) ;only melee

[ZedternalReborn.Config_SpecialWaveOverride]
MODEVERSION=20
SpecialWaveOverride_bAllowed=(Normal=False,Hard=False,Suicidal=True,HOE=True,Custom=True)
SpecialWaveOverride_SpecialWaves=(Wave=4,FirstPath="ZedternalReborn.WMSpecialWave_HellFire",SecondPath=,Probability=0.350000)
SpecialWaveOverride_SpecialWaves=(Wave=8,FirstPath="ZedternalReborn.WMSpecialWave_UnlimitedAmmo",SecondPath=,Probability=0.500000)
SpecialWaveOverride_SpecialWaves=(Wave=12,FirstPath="ZedternalReborn.WMSpecialWave_BloodyChainsaw",SecondPath=,Probability=0.350000)
SpecialWaveOverride_SpecialWaves=(Wave=16,FirstPath="ZedternalReborn.WMSpecialWave_Dosh",SecondPath=,Probability=0.500000)

[ZedternalReborn.Config_ZedBuff]
MODEVERSION=20
ZedBuff_bEnable=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
ZedBuff_bBonusDoshGivenPerBuff=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
ZedBuff_bBonusTraderTimeGivenPerBuff=(Normal=False,Hard=False,Suicidal=False,HOE=False,Custom=False)
ZedBuff_TraderTimeBonus=(Normal=25,Hard=25,Suicidal=25,HOE=25,Custom=25)
ZedBuff_DoshBonus=(Normal=2000,Hard=2000,Suicidal=2000,HOE=2000,Custom=2000)
ZedBuff_BuffWaves=(Waves=(3,7,10,14,17,20,23,27,30))
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Slasher_Enraged",MinWave=0,MaxWave=12)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Crawler_Health",MinWave=0,MaxWave=14)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Crawler_Faster",MinWave=0,MaxWave=12)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Gorefast_Damage",MinWave=0,MaxWave=12)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Gorefast_Enraged",MinWave=0,MaxWave=12)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_SpawnRate",MinWave=0,MaxWave=14)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Clot_Stronger",MinWave=0,MaxWave=14)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Stalker_Faster",MinWave=0,MaxWave=14)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Siren_ScreamRate",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Health",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Damage",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Speed",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_PukeMine",MinWave=10,MaxWave=14)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Siren_Heal",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Hostility",MinWave=14,MaxWave=20)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Husk_SuicideRate",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Scrake_Enraged",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Fleshpound_Stronger",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Health_II",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Damage_II",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Speed_II",MinWave=20,MaxWave=999)
ZedBuff_ZedBuffs=(Path="ZedternalReborn.WMZedBuff_Beefcake",MinWave=20,MaxWave=999)
