[ZedternalReborn.Config_GameOptions]
MODEVERSION=20
Game_bAllowZedternalUpgradeMenuCommand=(Normal=False,Hard=False,Suicidal=False,HOE=False,Custom=False)
Game_bZedternalUpgradeMenuCommandAllWave=(Normal=False,Hard=False,Suicidal=False,HOE=False,Custom=False)
Game_TimeBetweenWave=(Normal=90,Hard=80,Suicidal=70,HOE=60,Custom=60)
Game_TimeBetweenWaveIfPlayerDead=(Normal=100,Hard=100,Suicidal=70,HOE=70,Custom=70)
Game_DoshPickupDespawnTime=(Normal=90,Hard=90,Suicidal=90,HOE=90,Custom=90)
Game_ProjectilePickupDespawnTime=(Normal=150,Hard=150,Suicidal=150,HOE=150,Custom=150)
Game_WeaponPickupDespawnTime=(Normal=14400,Hard=14400,Suicidal=14400,HOE=14400,Custom=14400)
Game_bEnableDamageIndicators=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)

[ZedternalReborn.Config_Dosh]
MODEVERSION=20
Dosh_StartingDosh=(Normal=2000,Hard=2000,Suicidal=2000,HOE=2000,Custom=2000)
Dosh_NormalZedDoshMultiplier=(Normal=0.500000,Hard=0.500000,Suicidal=0.500000,HOE=0.500000,Custom=0.500000)
Dosh_ExtraNormalZedDoshIncPerPlayer=(Normal=0.100000,Hard=0.050000,Suicidal=0.050000,HOE=0.050000,Custom=0.050000)
Dosh_LargeZedDoshMultiplier=(Normal=0.850000,Hard=0.850000,Suicidal=0.750000,HOE=0.750000,Custom=0.750000)
Dosh_ExtraLargeZedDoshIncPerPlayer=(Normal=0.100000,Hard=0.100000,Suicidal=0.050000,HOE=0.050000,Custom=0.050000)
Dosh_BaseDoshWaveReward=(Normal=400,Hard=400,Suicidal=400,HOE=400,Custom=400)
Dosh_ExtraDoshRewardPerPlayer=(Normal=60,Hard=60,Suicidal=60,HOE=60,Custom=60)
Dosh_ExtraDoshPerWaveBonusMultiplier=(Normal=60,Hard=60,Suicidal=60,HOE=60,Custom=60)
Dosh_ExtraDoshPerPerkLevelBonusMultiplier=(Normal=1.000000,Hard=1.000000,Suicidal=1.000000,HOE=1.000000,Custom=1.000000)
Dosh_LateJoinerTotalDoshMultiplier=(Normal=0.700000,Hard=0.700000,Suicidal=0.700000,HOE=0.700000,Custom=0.700000)
Dosh_DeathPenaltyDoshPct=(Normal=0.020000,Hard=0.020000,Suicidal=0.020000,HOE=0.020000,Custom=0.020000)

[ZedternalReborn.Config_Player]
MODEVERSION=20
Player_bDropAllWeaponsWhenDead=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Player_StartingWeaponAmount=(Normal=1,Hard=1,Suicidal=1,HOE=1,Custom=1)
Player_StartingMaxHealth=(Normal=100,Hard=100,Suicidal=100,HOE=100,Custom=100)
Player_StartingMaxArmor=(Normal=100,Hard=100,Suicidal=100,HOE=100,Custom=100)
Player_StartingCarryWeight=(Normal=15,Hard=15,Suicidal=15,HOE=15,Custom=15)
Player_StartingMaxGrenadeCount=(Normal=5,Hard=5,Suicidal=5,HOE=5,Custom=5)
Player_HealAmountMultiplier=(Normal=1,Hard=1,Suicidal=1,HOE=1,Custom=1)
Player_DamageTakenMultiplierWhileHoldingMelee=(Normal=0.750000,Hard=0.750000,Suicidal=0.750000,HOE=0.750000,Custom=0.750000)
; DamageGiven
Player_DamageGiven=(DamageType="KFGame.KFDT_Fire",Multiplier=0.500000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Fire_Ground",Multiplier=0.400000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Fire_Napalm",Multiplier=0.400000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Explosive",Multiplier=0.400000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Explosive_Shrapnel",Multiplier=0.500000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Toxic_MedicGrenade",Multiplier=0.250000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Slashing",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Piercing",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGame.KFDT_Bludgeon",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_Shotgun",Multiplier=0.600000)
; BalancingWeapons
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Freeze_FreezeThrower",Multiplier=1.250000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Freeze_FreezeThrower_IceShards",Multiplier=1.750000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_CenterfireMB464",Multiplier=0.750000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_Winchester",Multiplier=0.750000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_SW500",Multiplier=0.800000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_M99",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_RailGun",Multiplier=0.900000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_HuskCannon",Multiplier=0.800000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_RPG7Impact",Multiplier=1.500000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_RPG7BackBlast",Multiplier=10.000000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_Pulverizer",Multiplier=2.500000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_EMP_HVStormCannon",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_HRG_Kaboomstick",Multiplier=0.850000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Piercing_Crossbow",Multiplier=1.300000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Piercing_CompoundBowSharpImpact",Multiplier=1.500000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_M14EBR",Multiplier=1.300000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_FNFal",Multiplier=1.200000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_MG3",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_MG3_Alt",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_Stoner63A",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_Minigun",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_MKB42",Multiplier=1.200000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_MosinNagant",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Piercing_MosinNagant",Multiplier=1.400000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_Minigun",Multiplier=1.100000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Bludgeon_HRG_BallisticBouncer_Shot",Multiplier=0.600000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_M4Shotgun",Multiplier=1.200000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_NailShotgun",Multiplier=1.300000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_ParasiteImplanter",Multiplier=1.200000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_C4",Multiplier=2.000000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_SealSqueal",Multiplier=1.300000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_SealSquealImpact",Multiplier=2.000000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Explosive_GravityImploder",Multiplier=1.300000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_GravityImploderImpactAlt",Multiplier=3.000000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_MicrowaveRifle",Multiplier=1.400000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Ballistic_G18",Multiplier=1.250000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Bludgeon_G18Shield",Multiplier=4.000000)
Player_DamageGiven=(DamageType="KFGameContent.KFDT_Bludgeon_G18Shield_Impulse",Multiplier=4.000000)
; DamageTaken
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Explosive_HuskSuicide",Multiplier=1.300000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_FleshpoundKing_ChestBeam",Multiplier=0.750000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Explosive_HansHEGrenade",Multiplier=0.750000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Explosive_PatMissile",Multiplier=0.750000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_EMP_MatriarchPlasmaCannon",Multiplier=0.600000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Sonic",Multiplier=1.500000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Toxic",Multiplier=2.000000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Fire_HuskFireball",Multiplier=1.250000)
Player_DamageTaken=(DamageType="KFGameContent.KFDT_Fire_HuskFlamethrower",Multiplier=1.500000)
Player_VampireEffect=(DamageType="KFGame.KFDT_Bludgeon",HealAmount=3)
Player_VampireEffect=(DamageType="KFGame.KFDT_Piercing",HealAmount=3)
Player_VampireEffect=(DamageType="KFGame.KFDT_Slashing",HealAmount=3)

[ZedternalReborn.Config_Trader]
MODEVERSION=20
Trader_MaxWeapon=(Normal=1052,Hard=1052,Suicidal=1052,HOE=1052,Custom=1052)
Trader_StartingWeaponNumber=(Normal=3,Hard=3,Suicidal=3,HOE=3,Custom=3)
Trader_NewWeaponEachWave=(Normal=3,Hard=3,Suicidal=3,HOE=3,Custom=3)
Trader_AmmoPriceMultiplier=(Normal=0.500000,Hard=0.500000,Suicidal=0.500000,HOE=0.500000,Custom=0.500000)
Trader_ArmorPrice=(Normal=2,Hard=2,Suicidal=2,HOE=2,Custom=2)
Trader_GrenadePrice=(Normal=40,Hard=40,Suicidal=40,HOE=40,Custom=40)

[ZedternalReborn.Config_TraderVoice]
MODEVERSION=20
TraderVoice_bUsePatriarchTrader=True
TraderVoice_bUseHansTrader=True
TraderVoice_bUseDefaultTrader=True
TraderVoice_bUseObjectiveTrader=True
TraderVoice_bUseLockheartTrader=True
TraderVoice_bUseSantaTrader=True

[ZedternalReborn.Config_Voting]
MODEVERSION=20
Voting_SkipTraderVotingPercentage=(Normal=0.750000,Hard=0.750000,Suicidal=0.750000,HOE=0.500000,Custom=0.500000)
Voting_PauseGameVotingPercentage=(Normal=0.750000,Hard=0.750000,Suicidal=0.750000,HOE=0.500000,Custom=0.500000)
Voting_bEnablePauseButton=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Voting_bAllowTraderDuringPause=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Voting_bAllowPickupsDuringPause=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)

[ZedternalReborn.Config_Pickup]
MODEVERSION=20
Pickup_bEnablePickups=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Pickup_bEnableAmmoPickups=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Pickup_bEnableWeaponPickups=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Pickup_bArmorSpawnOnMap=(Normal=True,Hard=True,Suicidal=True,HOE=True,Custom=True)
Pickup_AmmoPickupBasePercentage=(Normal=0.400000,Hard=0.350000,Suicidal=0.300000,HOE=0.750000,Custom=0.750000)
Pickup_AmmoPickupPercentageIncPerWave=(Normal=0.040000,Hard=0.030000,Suicidal=0.020000,HOE=0,Custom=0)
Pickup_AmmoPickupMaxPercentage=(Normal=0.950000,Hard=0.900000,Suicidal=0.850000,HOE=0.750000,Custom=0.750000)
Pickup_ItemPickupBasePercentage=(Normal=0.450000,Hard=0.350000,Suicidal=0.250000,HOE=0.100000,Custom=0.100000)
Pickup_ItemPickupPercentageIncPerWave=(Normal=0.030000,Hard=0.025000,Suicidal=0.020000,HOE=0.015000,Custom=0.015000)
Pickup_ItemPickupMaxPercentage=(Normal=0.900000,Hard=0.800000,Suicidal=0.700000,HOE=0.550000,Custom=0.550000)
Pickup_bOverrideKismetPickups=True

[ZedternalReborn.Config_Map]
MODEVERSION=20
Map_Settings=(MapName="KF-Random_Holdout",Difficulty=(0,1,2,3,4),StartingDosh=4000,StartingWave=1,FinalWave=30,StartingTraderTime=0,ZedNumberScale=1.000000,ZedSpawnRate=8.000000,ZedStuckThreshold=4,ZedStuckTimeout=150,AllTraders=False,EnableAmmoPickups=True,EnableWeaponPickups=True,ArmorSpawnOnMap=True,OverrideKismetPickups=True,AmmoPickupBase=0.400000,AmmoPickupIncPerWave=0.040000,AmmoPickupMax=0.950000,ItemPickupBase=0.450000,ItemPickupIncPerWave=0.030000,ItemPickupMax=0.900000)
Map_Settings=(MapName="KF-Simple_Holdout",Difficulty=(0,1,2,3,4),StartingDosh=3000,StartingWave=1,FinalWave=30,StartingTraderTime=0,ZedNumberScale=1.000000,ZedSpawnRate=8.000000,ZedStuckThreshold=4,ZedStuckTimeout=150,AllTraders=False,EnableAmmoPickups=True,EnableWeaponPickups=True,ArmorSpawnOnMap=True,OverrideKismetPickups=True,AmmoPickupBase=0.400000,AmmoPickupIncPerWave=0.040000,AmmoPickupMax=0.950000,ItemPickupBase=0.450000,ItemPickupIncPerWave=0.030000,ItemPickupMax=0.900000)
Map_Settings=(MapName="KF-Zedternal_Holdout",Difficulty=(0,1,2,3,4),StartingDosh=2000,StartingWave=1,FinalWave=30,StartingTraderTime=0,ZedNumberScale=1.000000,ZedSpawnRate=8.000000,ZedStuckThreshold=4,ZedStuckTimeout=150,AllTraders=False,EnableAmmoPickups=True,EnableWeaponPickups=True,ArmorSpawnOnMap=True,OverrideKismetPickups=True,AmmoPickupBase=0.400000,AmmoPickupIncPerWave=0.040000,AmmoPickupMax=0.950000,ItemPickupBase=0.450000,ItemPickupIncPerWave=0.030000,ItemPickupMax=0.900000)